Messages:
  no-params: "&bInvalid arguments"
  invalid-measure: "&bInvalid measure"
  scale-change: "&fTransforming &b%measure%cm &fto new scale for &b%player%&f: &b%scale%"
  exceeded-measure: "&bThat measurement is below the maximum or minimum"
  no-permission: "&cYou dont have permissions"

Config:
  maximum-measure: 210
  minimum-measure: 135

